"""Generates docs/figures/deadlift_double_count.png for the README. No
invented numbers: the 'before' sequence is the exact disclosed gap list from
the Findings section, the 'after' sequence is recomputed directly from
output/session.json.

The confidence-by-distance figure that used to live in this file is now
generated by build_confidence_figure.py instead: this file's version bucketed
with an epsilon on the lower edge (dist > lo - 1e-9), which double-counted
samples sitting exactly on bucket boundaries (258 bucketed samples out of
155) and produced means that did not match the README's table."""

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

OUT_DIR = Path(__file__).parent.parent / "docs" / "figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)

INK = "#1a1a1a"
DIM = "#6b6b66"
BG = "#faf9f6"
MEASURED = "#2b2b2b"
HIGH_CONF = "#8a7530"
LOW_CONF = "#8b3a2f"

plt.rcParams.update({
    "font.family": "monospace",
    "axes.edgecolor": DIM,
    "text.color": INK,
    "axes.labelcolor": INK,
    "xtick.color": DIM,
    "ytick.color": DIM,
    "figure.facecolor": BG,
    "axes.facecolor": BG,
})

# ---------------------------------------------------------------------
# Figure 1: deadlift double-counting, before and after the spacing fix.
# "Before" gaps are the exact 19 values reported in the Findings section
# (1.0s minimum peak spacing). "After" gaps are recomputed here directly
# from the current pipeline output (1.4s minimum peak spacing).
# ---------------------------------------------------------------------
before_gaps = [2.7, 1.1, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.1,
               1.0, 1.3, 1.9, 1.2, 2.0, 1.1, 1.1, 3.0, 1.9]

with open(Path(__file__).parent.parent / "output" / "session.json") as f:
    session = json.load(f)
dead = [s for s in session["sets"] if s["label"] == "dead-medium1-rpe6"][0]
rep_times = [r["t"] for r in dead["reps"]]
after_gaps = list(np.round(np.diff(rep_times), 2))
assert len(dead["reps"]) == 11, "rep count changed, regenerate this figure from source"

fig, axes = plt.subplots(2, 1, figsize=(9, 5.5), sharex=False)

for ax, gaps, title, spacing in [
    (axes[0], before_gaps, f"Before fix — 1.0s minimum spacing — {len(before_gaps)+1} reps detected", 1.0),
    (axes[1], after_gaps, f"After fix — 1.4s minimum spacing — {len(after_gaps)+1} reps detected", 1.4),
]:
    colors = [LOW_CONF if g < 1.4 else MEASURED for g in gaps]
    ax.bar(range(1, len(gaps) + 1), gaps, color=colors, width=0.6)
    ax.axhline(1.4, color=DIM, linewidth=1, linestyle=(0, (3, 2)))
    ax.set_title(title, fontsize=10, loc="left", color=INK, pad=8)
    ax.set_ylabel("gap (s)", fontsize=8.5)
    ax.set_ylim(0, 4.5)
    ax.set_xticks(range(1, len(gaps) + 1))
    ax.set_xlabel("gap index (between consecutive detected reps)", fontsize=8.5)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

axes[0].text(len(before_gaps) - 0.5, 4.1,
             "9 consecutive gaps ≈1.0s\n= liftoff + lockout counted twice",
             fontsize=8, color=LOW_CONF, ha="right", va="top")

fig.suptitle("Deadlift set (dead-medium1-rpe6): rep-to-rep gap timing, before and after the spacing fix",
             fontsize=11, color=INK, y=0.99)
fig.tight_layout(rect=[0, 0, 1, 0.94])
fig.savefig(OUT_DIR / "deadlift_double_count.png", dpi=180, facecolor=BG)
plt.close(fig)
print("wrote", OUT_DIR / "deadlift_double_count.png")

# The confidence-by-distance figure is generated by
# build_confidence_figure.py, which imports the bucketing from
# analyze_findings.py so the figure cannot drift from the README's table.
